### ISSUE TITLE
x86/x64

### ISSUE THREAD

**Issue by viktormax3** [JoshuaMKW/GeckoLoader#2]
Could you make a version compatible with x86 processors ?, this only works on x64

**Comment by JoshuaMKW** [comment]
Yes, I will try to do so. Hopefully I should have something in the next few days.

**Comment by JoshuaMKW** [comment]
Alright so for now I have uploaded a new version of the release, which includes the python script version for those on incompatible systems. You can use this by replacing ".\GeckoLoader" with "python GeckoLoader.py". You will need to have python 3.8 installed and have it added to your PATH, but as long as you do this it will work on all systems.

I am still working on getting a proper x86 exe made, it's just I've been rather busy lately so I hope you understand

**Comment by JoshuaMKW** [comment]
Sadly, my pc is too slow to run a virtual machine for compiling 32 bit exes, so I cant compile one for the release build. You can simply run python 3.8 in the command line using the files in the py folder of this release. I'm marking this as resolved
