### ISSUE TITLE
GeckoLoader v7.1.0: error: There are no unused sections left for GeckoLoader to use!

### ISSUE THREAD

**Issue by hueybud** [JoshuaMKW/GeckoLoader#3]
I get the error in the title after filling my DOL (Super Mario Strikers) with maybe 150 Gecko code lines. Not sure if I'm doing something wrong or if it's the program. I am entering C2 codes one at a time and filling out their corresponding Codehook Addresses because it doesn't work if I don't. I am using the destination DOL as the source so that I can compound the changes onto each other. The source file is a TXT file with the individual C2 code.

**Comment by JoshuaMKW** [comment]
Well the issue is within your message. You are compounding changes onto the same DOL. This uses more and more sections until none remain. Instead patch the original DOL with all your codes at once into a new dol. I'll leave this issue open since I plan to eventually work around this.

**Comment by hueybud** [comment]
Ok, even switching that out, I cannot do multiple C2s at once or it does not work. It tells me that it fails to find a hook address. And I can only provide one hook per C2, so I'm stuck there.

**Comment by JoshuaMKW** [comment]
Well C2 codes hook at runtime, GeckoLoader doesn't care about them. What that means is that the hook type for the codehandler itself cant be found. I imagine you have it set to VI rn which is the default, so try GX or PAD and if those fail too you could ask someone to find a manual address for you to enter in advanced settings

**Comment by hueybud** [comment]
Voila! Changing it to GX instantly worked. Thank you for your quick and helpful response Joshua!

**Comment by JoshuaMKW** [comment]
You're welcome
